#([название],[тип],[отображать в интерфейсе],[из сервиса])
columns_type=[('inn','str',True,False)
        ,('status','str',True,False)
        ,('info','str',True,False)
        ,('company','str',True,False)
        ,('corp_id','str',False,False)

        ,('id','str',False,True)
        ,('name','str',False,True)
        ,('okud','str',True,True)
        ,('form_period','str',True,True)
        ,('formatted_period','str',False,True)
        ,('reported_period','str',True,True)
        ,('period','str',False,True)
        ,('period_comment','str',False,True)
        ,('dept_nsi_id','str',False,True)
        ,('dept_nsi_code','str',False,True)
        ,('type_exam','str',False,True)
        ,('index','str',True,True)
        ,('description','str',False,True)
        ,('act_num','str',False,True)
        ,('act_date','str',False,True)
        ,('end_time','str',True,True)
        ,('comment','str',True,True)
        ,('updatingDate','str',False,True)
        ,('isValid','str',False,True)
        ,('periodicity','str',False,True)
        ,('periodNum','str',False,True)
        ,('periodYear','str',False,True)
                                        
        ]